target 'OCTemplate' do
	pod 'AFNetworking', '~> 3.2.1'    	
	pod 'SDWebImage', '~> 4.4.2'
	pod 'Masonry', '~> 1.0.2'
	pod 'BlocksKit', '~> 2.2.5'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'MJRefresh', '~> 3.1.12'
end
